---
title: junyin.org
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: sayhi@junyin.org
description: "I blog about what might benefit people like me. \n"
baseurl: ''
url: http://junyin.org
github_username: acadabun
markdown: kramdown
