# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: junyin.org
email: sayhi@junyin.org
description: > # this means to ignore newlines until "baseurl:"
  I blog about what might benefit people like me. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://junyin.org" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  acadabun

# Build settings
markdown: kramdown
